framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true              # Better for database performance
                    check_delayed_interval: 60000 # Check for delayed messages every 60s
                retry_strategy:
                    max_retries: 3               # Max retry attempts
                    delay: 1000                  # Initial delay in ms (1s)
                    multiplier: 2                # Exponential backoff (1s, 2s, 4s)
                    max_delay: 10000             # Max 10s between retries

            failed:
                dsn: 'doctrine://default?queue_name=failed'

            sync: 'sync://'  # Uncommented for emergency use

        buses:
            messenger.bus.default: ~

        routing:
            # Email messages (now with proper retry handling)
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async


            # Notification messages
            'Symfony\Component\Notifier\Message\ChatMessage': async
            'Symfony\Component\Notifier\Message\SmsMessage': async

            # Example for custom messages
            # 'App\Message\YourMessage': async